### ISSUE TITLE
Can't set up token in Home Assistant Add-On (Raspberry Zircon3D Beta2)

### ISSUE THREAD

**Issue by acenuke** [lichr/zircon-ha-repository#1] opened 2024-04-27 22:03 UTC
Hello,

Thanks for releasing the add-on for Raspberry PI in beta2 (v0.3.2). On a few of my instances, the web page to enter the auth token is not loading correctly and I can't enter the token (see below).

![image](https://github.com/lichr/zircon-ha-repository/assets/10014367/82e22afa-e98f-4326-ac44-fc8543823888)

I tried to uninstall/reinstall, even remove the repository, but nothing works. 

Thanks for the good work!

**Comment by acenuke** [comment] 2024-04-29 15:57
I found the issue: if you try to configure using the NABU CASA URL, it won't work. You need to use the local IP (and be on your local network to configure)

**Comment by dzegarra** [comment] 2024-07-02 13:59
Confirmed. That's a crucial detail the creator(s) forgot to include in their official docs 🤦‍♂️. I had finally been able to authenticate, after 9 months. 

But, It seems this proxy add-on only works when HA-UI's is accessed using an unsecure URL. I use a domain name even in my house, so I can access it from within and remotely. This proxy does not work when accessed non-locally. 

Are there plans to "fix" that? Or is by design?

**Comment by chris-xinhai-li** [comment] 2024-09-29 03:31
Hello @acenuke  @dzegarra, 

Thank you for your valuable feedback. Until recently, our development priorities have been focused on refining the UI and data integrations, which is why this issue has been on hold for so long. We hope you understand.

We are planning to deliver another beta release in late October, where we will address this connection issue. If you could provide more details about your environment setup—are you using Nabu Casa services, local HTTPS, or do you need remote access to our UI? Such information will help us set up a lab environment to replicate and resolve the issue more accurately.

Your assistance would be greatly appreciated.

**Comment by dzegarra** [comment] 2024-09-29 14:51
I use http on local, and https when accessed from outside. I just had my routed forward the 443 and 80 ports traffic to a reverse proxy server running on my network to create the SSL certs and forward the traffic to my HASS installation. 
I noticed all the UIs of the HASS add-ons are available both from local and outside because HASS proxies them to make them look they come from the same HASS UI. That's how I'm able to access Zigbee2Mqtt or even tne embedded VSCode from my local network without HTTPS and from outside with SSL.

**Comment by chris-xinhai-li** [comment] 2024-11-24 08:28
We just released beta3 and proxy addon 0.5.0, which includes fix for this issue, we tested with nabu-casa and other scenarios, hopefully can also work on your environment.

**Closed** 2024-11-29 22:11 UTC
Labels: enhancement, beta3
